### ISSUE TITLE
ebuild fails with systemd

### ISSUE THREAD

**Issue by jyoung15** [FRRouting/gentoo-overlay#45]
frr-6 and frr-7 ebuilds fail with the following error:
```OSError: [Errno 2] No such file or directory: '/var/tmp/portage/net-misc/frr-7.0/files/systemd/no.service'```

Issue appears to be in `src_install()` function with usage of `usex`.  Per ebuild(5):
```
usex <USE flag> [true output] [false output] [true suffix] [false suffix]
       If  USE  flag  is  set,  echo  [true output][true suffix] (defaults to "yes"), otherwise echo [false output][false suffix] (defaults to "no").
```

Since there is no false output provided, it defaults to "no".   Suggest using empty string in false argument as workaround - ` $(usex bgp bgpd "")`, etc.

**Comment by f0o** [comment]
Seems accurate, I'll fix it this tomorrow/weekend.

Thanks for the report!
