### ISSUE TITLE
user.eclass could not be found by inherit()

### ISSUE THREAD

**Issue by onkelbeh** [FRRouting/gentoo-overlay#76]
user.eclass was removedyesterday, https://github.com/gentoo/gentoo/commit/dd1ebe44dd72ec2435687095d063644ec94d8b8e
looks like some Ebuilds have to be touched, a lot of newer versions are missing, anyway.

```
 *   user.eclass could not be found by inherit()
 *
 * Call stack:
 *           ebuild.sh, line 614:  Called source '/var/db/repos/frr-gentoo/net-misc/frr/frr-7.1-r2.ebuild'
 *   frr-7.1-r2.ebuild, line   6:  Called inherit 'autotools' 'eutils' 'flag-o-matic' 'multilib' 'pam' 'readme.gentoo-r1' 'systemd' 'tmpfiles' 'user' 'vcs-snapshot'
 - *           ebuild.sh, line 259:  Called die
 * The specific snippet of code:
 *   		[[ -z ${location} ]] && die "${1}.eclass could not be found by inherit()"
 *
```
 
Thanks a lot for this great piece of software.

**Comment by f0o** [comment]
I'll have a look

**Comment by f0o** [comment]
I think the best would be to retire those versions, I dont think there's any good in keeping <=7.1 ebuilds updated.

**Comment by onkelbeh** [comment]
just add 8.4.1, drop all with user inherited.

**Comment by onkelbeh** [comment]
ups just noticed during cleanup: frr, libyang & rtrlib are up to date in the main repo, so this one can be dropped.

**Comment by f0o** [comment]
only FRR >=7.4 is now available, this should fix the broken ebuilds since those dont use user eclass.

**Comment by onkelbeh** [comment]
8.4.1 is in Gentoo's main repo.
