### ISSUE TITLE
outdated repository

### ISSUE THREAD

**Issue by jkroonza** [FRRouting/gentoo-overlay#79]
Hi,

We've got newer versions in ::gentoo main repository, can we please request that this overlay be killed?

Thanks!

Kind regards,
Jaco

**Comment by f0o** [comment]
Sure - the overlay was deprecated after frrouting made it into ::gentoo, I'll make the PR to remove it

**Comment by f0o** [comment]
https://github.com/gentoo/api-gentoo-org/pull/711
